In [21]:
from google.colab import files
import pandas as pd
import os

# Upload Excel file
uploaded = files.upload()

# Get the actual filename Colab assigned
file_name = list(uploaded.keys())[0]

print("Uploaded filename:", file_name)
print("Full path:", os.path.abspath(file_name))

# Load Excel
dataset = pd.read_excel(file_name)

print("\nDataset loaded successfully!")
print("Shape:", dataset.shape)

display(dataset.head())

Saving Expense Dataset.xlsx to Expense Dataset (1).xlsx
Uploaded filename: Expense Dataset (1).xlsx
Full path: /content/Expense Dataset (1).xlsx

Dataset loaded successfully!
Shape: (110000, 21)

,User_ID,Year,Month,Monthly_Income,Bills,Education,Entertainment,Food,Health,Shopping,...,Travel,Total_Expense,Savings,Savings_Rate,Expense_Ratio,Average_Daily_Expense,Weekend_Spending_Percentage,Transaction_Count,Spending_Profile,NextMonthExpense
0,U00001,2025,1,146919.89,18181.21,24989.66,4224.07,1286.79,2855.04,6148.05,...,18804.57,83974.51,62945.38,0.4284,0.5716,2799.15,21.64,64,Conservative,82862.49
1,U00001,2025,2,136686.15,2962.98,1506.22,4859.21,33775.74,4605.29,8628.82,...,14322.37,82862.49,53823.66,0.3938,0.6062,2762.08,19.40,30,Conservative,82554.05
2,U00001,2025,3,139109.12,39399.34,3482.08,8255.10,4296.83,4024.55,451.19,...,11290.27,82554.05,56555.07,0.4066,0.5934,2751.80,34.07,105,Conservative,84221.71
3,U00001,2025,4,137749.26,2944.78,21537.40,2469.06,1411.24,6061.04,38263.22,...,2498.67,84221.71,53527.55,0.3886,0.6114,2807.39,34.08,72,Conservative,87388.16
4,U00001,2025,5,143849.44,4196.16,20147.00,7091.05,15472.78,15524.34,11867.61,...,1463.44,87388.16,56461.28,0.3925,0.6075,2912.94,21.17,54,Conservative,92336.05

In [22]:
print("Dataset Shape:", dataset.shape)

print("\nMissing Values:")
print(dataset.isnull().sum())

print("\nDuplicate Rows:")
print(dataset.duplicated().sum())

print("\nData Types:")
print(dataset.dtypes)

Dataset Shape: (110000, 21)

Missing Values:
User_ID                        0
Year                           0
Month                          0
Monthly_Income                 0
Bills                          0
Education                      0
Entertainment                  0
Food                           0
Health                         0
Shopping                       0
Transport                      0
Travel                         0
Total_Expense                  0
Savings                        0
Savings_Rate                   0
Expense_Ratio                  0
Average_Daily_Expense          0
Weekend_Spending_Percentage    0
Transaction_Count              0
Spending_Profile               0
NextMonthExpense               0
dtype: int64

Duplicate Rows:
0

Data Types:
User_ID                         object
Year                             int64
Month                            int64
Monthly_Income                 float64
Bills                          float64
Education                      float64
Entertainment                  float64
Food                           float64
Health                         float64
Shopping                       float64
Transport                      float64
Travel                         float64
Total_Expense                  float64
Savings                        float64
Savings_Rate                   float64
Expense_Ratio                  float64
Average_Daily_Expense          float64
Weekend_Spending_Percentage    float64
Transaction_Count                int64
Spending_Profile                object
NextMonthExpense               float64
dtype: object

In [23]:
print(dataset["Spending_Profile"].value_counts())

Spending_Profile
Conservative    37422
Moderate        36531
Heavy           36047
Name: count, dtype: int64

In [24]:
print("Unique Users:", dataset["User_ID"].nunique())

print("\nRecords per user:")
print(dataset.groupby("User_ID").size().describe())

Unique Users: 10000

Records per user:
count    10000.0
mean        11.0
std          0.0
min         11.0
25%         11.0
50%         11.0
75%         11.0
max         11.0
dtype: float64

In [25]:
dataset[
    dataset["User_ID"] == "U00001"
][
    ["Year", "Month", "Total_Expense", "NextMonthExpense"]
].head(15)

    Year  Month  Total_Expense  NextMonthExpense
0   2025      1       83974.51          82862.49
1   2025      2       82862.49          82554.05
2   2025      3       82554.05          84221.71
3   2025      4       84221.71          87388.16
4   2025      5       87388.16          92336.05
5   2025      6       92336.05          97358.21
6   2025      7       97358.21         102066.67
7   2025      8      102066.67         110298.84
8   2025      9      110298.84         124169.98
9   2025     10      124169.98         134029.25
10  2025     11      134029.25         131880.87

In [26]:
dataset_encoded = dataset_encoded.sort_values(
    by=["User_ID", "Year", "Month"]
).reset_index(drop=True)

print(dataset_encoded.shape)

(110000, 23)

In [27]:
X = dataset_encoded.drop(
    columns=[
        "User_ID",
        "NextMonthExpense"
    ]
)

y = dataset_encoded["NextMonthExpense"]

print("Number of input features:", X.shape[1])
print("Target:", y.name)

print("\nFeatures:")
print(X.columns.tolist())

Number of input features: 21
Target: NextMonthExpense

Features:
['Year', 'Month', 'Monthly_Income', 'Bills', 'Education', 'Entertainment', 'Food', 'Health', 'Shopping', 'Transport', 'Travel', 'Total_Expense', 'Savings', 'Savings_Rate', 'Expense_Ratio', 'Average_Daily_Expense', 'Weekend_Spending_Percentage', 'Transaction_Count', 'Spending_Profile_Conservative', 'Spending_Profile_Heavy', 'Spending_Profile_Moderate']

In [28]:
print("X Train:", X_train.shape)
print("X Test :", X_test.shape)

print("\ny Train:", y_train.shape)
print("y Test :", y_test.shape)

print("\nMissing training values:", X_train.isnull().sum().sum())
print("Missing testing values :", X_test.isnull().sum().sum())

X Train: (80000, 21)
X Test : (30000, 21)

y Train: (80000,)
y Test : (30000,)

Missing training values: 0
Missing testing values : 0

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

linear_predictions = linear_model.predict(X_test)

linear_mae = mean_absolute_error(y_test, linear_predictions)
linear_rmse = np.sqrt(mean_squared_error(y_test, linear_predictions))
linear_r2 = r2_score(y_test, linear_predictions)

print("LINEAR REGRESSION")
print("--------------------------")
print("MAE :", round(linear_mae, 2))
print("RMSE:", round(linear_rmse, 2))
print("R²  :", round(linear_r2, 4))

LINEAR REGRESSION
--------------------------
MAE : 8140.61
RMSE: 11625.68
R²  : 0.9626